import = [
  "~/.config/alacritty/toyko-night.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dynamic_title = true
option_as_alt = "OnlyRight"
decorations = "None"
startup_mode = "Maximized"
opacity = 0.95

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 18
