import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dynamic_title = true
option_as_alt = "OnlyRight"
decorations = "None"
dimensions = { columns = 161, lines = 43 }
position = { x = 20, y = 1000 }

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 18

